---
version: 2.1

# Enables dynamic config loading
setup: true

jobs:
  setup:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/prod-config.yml

workflows:
  setup_workflow:
    jobs:
      - setup:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

orbs:
  continuation: circleci/continuation@1.1.0
